### PR TITLE
Added basetypes for latest Vulkan 1.0.43, No solution for line 147 of vk.xml though

### PR DESCRIPTION
**Pull request by pocdn**
build.py:
  is updated with basetypes missing to use latest 1.0.43 version of vk.xml from Khronos doc.
  also had to deal with vk.xml having a line containing troublesome 
    <enum value="(~0U-1)" name="VK_QUEUE_FAMILY_EXTERNAL_KHX"/>
  so added regex to "translate_api_constants" to work around "(~0U-1)" however, I am not confident 
  that is the best fix.
example.py:
  file change can be ignored since ,y local GPU didn't have that validation layer

Biggest problem I found no way around was line 147 in the original spec/vk.xml file. 
I couldn't get the build.py file
to deal with <type name="int"/> so I did an unsatisfactory edit to the spec/vk.xml file
and changed line 147 to .

Any idea how to fix build.py to deal with original line 147: <type name="int"/>

### CODE REVIEW

**Comment by cheery** [comment]
Hi @pocdn and thanks for this update! I merge it straight away.

`translate_api_constants` is bit of a hack I agree. I have a fix for that `<type name="int"/>` in the `vkstruct_json.py`. I'll copy it over.

**Comment by cheery** [comment]
@pocdn There you go! Anything else? If you have plans related to `vkstruct` that I could hear, I would like to hear them.

**Comment by pocdn** [comment]
Thanks for the new code changes. Very helpful.

So far so good, nothing else since I am learning to use your library. My plans with vkstruct are to investigate using python and vulkan, mainly for compute tasks. If I ever get some interesting examples using vkstruct I will share them if that is helpful.

**Comment by cheery** [comment]
I also added in the enumerations from the extensions. These are available in the `vkstruct_json.py` by the last commit. It will take little bit of thinking to adjust it for `vkstruct.py`, but should be possible.

**Pull request merged**
